#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mirea.Snar2017.Navigate.Resource", IsApplication=true)]

namespace Mirea.Snar2017.Navigate
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int Expand = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ExpandIn = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Rotate = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Shrink = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ShrinkOut = 2130968580;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int Black = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int BlueDark = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int BlueLight = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int GrayDark = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int GrayLight = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int GrayVeryDark = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int GrayVeryLight = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int SaladDark = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int SaladLight = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int White = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ApplicationIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Border = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int RedButton = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int WhiteButton = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000e
			public const int AccelerometerPlotView = 2131230734;
			
			// aapt resource value: 0x7f080015
			public const int CalibrateButton = 2131230741;
			
			// aapt resource value: 0x7f080000
			public const int CalibrateTextView = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int CalibrateXButton = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int CalibrateYButton = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int CalibrateZButton = 2131230723;
			
			// aapt resource value: 0x7f080012
			public const int ClearLogButton = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int FilterSettingsButton = 2131230740;
			
			// aapt resource value: 0x7f08000f
			public const int GyroPlotView = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int LogButton = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int MagnetometerPlotView = 2131230736;
			
			// aapt resource value: 0x7f08000d
			public const int RootLinearLayot = 2131230733;
			
			// aapt resource value: 0x7f080004
			public const int RootLinearLayot1 = 2131230724;
			
			// aapt resource value: 0x7f080013
			public const int ShowLogPlayerButton = 2131230739;
			
			// aapt resource value: 0x7f080009
			public const int ekspButton = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int ekspTV = 2131230730;
			
			// aapt resource value: 0x7f080008
			public const int ekspText = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int madjButton = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int madjTV = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int madjText = 2131230725;
			
			// aapt resource value: 0x7f08000c
			public const int magnSwitch = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int magnetText = 2131230731;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CalibrateMenu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FilterSets = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LogPl = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainMenu = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Calibrate = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int Clear = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int FilterSettings = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int LogPlayer = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int StartLog = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int StopLog = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int ekspButton = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int madjButton = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int magnetometr = 2131099657;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int ButtonText = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int DarkAndGray = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
